name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v20.16.0

      - name: Install dependencies
        run: |
          npm install  # Instala todas as dependências do seu projeto

      - name: Run Cypress tests
        run: |
          npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/results  # Comando para rodar os testes com relatório

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/results  # Modifique se for usar outro caminho para os relatórios
